### ISSUE TITLE
ValueError: Output datum insufficently specified

### ISSUE THREAD

**Issue by mythosjohn** [noaa-ocs-hydrography/vyperdatum#44]
With latest main (28b63b3) and vdatum vdatum_all_20220511 from NOAA I observe `ValueError: Output datum insufficently specified`. 

- I tried poking around the code for a while but it's unclear why this doesn't work. 
- Tried all examples
- I also tried a variety of other datums, including obvious/easy ones, nothing works.
- I attempted to run the unit tests but those almost all fail.

It's probably something with my environment but I don't have enough info to debug what's wrong. I'm running ubuntu 20.04 and a conda environment with all requested packages.

Is there a way to enable detailed debug tracing? Any suggestions would be appreciated, thank you!

More details below.

Here is the output of running a quick test script.
(vyper) **********:~/vyperdatum$ python3 ./test.py
Output datum insufficently specified
Output datum insufficently specified
Traceback (most recent call last):
  File "./test.py", line 11, in <module>
    vp.transform_points(6319, 'mllw', x, y, z=z)
  File "/home/john/vyperdatum/vyperdatum/points.py", line 60, in transform_points
    self.x, self.y, self.z, self.unc, self.region_index = self.transform_dataset(x, y, z,
  File "/home/john/vyperdatum/vyperdatum/core.py", line 395, in transform_dataset
    self.log_error('Output datum insufficently specified', ValueError)
  File "/home/john/vyperdatum/vyperdatum/core.py", line 63, in log_error
    raise exception(msg)
ValueError: Output datum insufficently specified

Contents of test.py (same as first example in README.md)
```
import numpy as np
from vyperdatum.points import VyperPoints
vp = VyperPoints(vdatum_directory='/home/john/Downloads/vdatum_all_20220511/vdatum/')

vp = VyperPoints()
x = np.array([-76.19698, -76.194, -76.198])
y = np.array([37.1299, 37.1399, 37.1499])
z = np.array([10.5, 11.0, 11.5])

vp.transform_points(6319, 'mllw', x, y, z=z)
```

For what it's worth I tried an earlier vdatum package:

```
Performing hash comparison to identify VDatum version, should only run once for a new VDatum directory...
Found vdatum_4.2_20210603
Generated new version file: /home/john/Downloads/vdatum_all_20210602/vdatum/vdatum_vyperversion.txt
Output datum insufficently specified
Output datum insufficently specified
Traceback (most recent call last):
  File "./test.py", line 12, in <module>
    vp.transform_points(6319, 'mllw', x, y, z=z)
  File "/home/john/vyperdatum/vyperdatum/points.py", line 60, in transform_points
    self.x, self.y, self.z, self.unc, self.region_index = self.transform_dataset(x, y, z,
  File "/home/john/vyperdatum/vyperdatum/core.py", line 395, in transform_dataset
    self.log_error('Output datum insufficently specified', ValueError)
  File "/home/john/vyperdatum/vyperdatum/core.py", line 63, in log_error
    raise exception(msg)
ValueError: Output datum insufficently specified
```

**Comment by GlenRice-NOAA** [comment]
At first glance I would guess that the target system is only vertical and needs a horizontal component.

Thanks for your interest in Vyperdatum so what is on GitHub right now is a bit stale.  We are reconfiguring Vyperdatum around new entries to the PROJ registry that will hopefully make Vyperdatum more of a thin wrapper around PROJ, so this is where our effort is currently focused.

**Comment by FariborzDaneshvar-NOAA** [comment]
I'm also getting this ValueError! Here are my commands:
```
import numpy as np
from vyperdatum.points import VyperPoints
vp = VyperPoints(vdatum_directory='path/to/vdatum')  #which I used `vdatum_all_20220511`

x = np.array([-76.19698, -76.194, -76.198])
y = np.array([37.1299, 37.1399, 37.1499])
z = np.array([10.5, 11.0, 11.5])
vp.transform_points(6319, 'mllw', x, y, z=z)
```

But it returned this error:
```
ValueError                                Traceback (most recent call last)                        
Cell In[15], line 1                                                                                
----> 1 vp.transform_points(6319, 'mllw', x, y, z=z)

File /nhc/Fariborz.Daneshvar/miniconda3/envs/vyper/lib/python3.8/site-packages/vyperdatum/points.py:60, 
in VyperPoints.transform_points(self, input_datum, output_datum, x, y, z, include_vdatum_uncertainty, 
include_region_index, sample_distance)                                                          
     57 self.set_output_datum(output_datum)
     59 if not sample_distance:  
---> 60     self.x, self.y, self.z, self.unc, self.region_index = self.transform_dataset(x, y, z,       
     61                                                                                  include_vdatum_uncertainty=include_vdatum_uncertainty,
     62                                                                                  include_region_index=include_region_index)
     63 else:
     64     extents = (float(np.nanmin(x)), float(np.nanmin(y)), float(np.nanmax(x)), float(np.nanmax(y)))        

File /nhc/Fariborz.Daneshvar/miniconda3/envs/vyper/lib/python3.8/site-packages/vyperdatum/core.py:395, 
in VyperCore.transform_dataset(self, x, y, z, include_vdatum_uncertainty, include_region_index)    
    393     self.log_error('Input datum insufficently specified', ValueError)  
    394 if not self.out_crs.is_valid:
--> 395     self.log_error('Output datum insufficently specified', ValueError)
    397 if z is not None and not self.in_crs.is_height:  
    398     z = z.copy()  # do not alter the array input                                                                                                                                              
	
File /nhc/Fariborz.Daneshvar/miniconda3/envs/vyper/lib/python3.8/site-packages/vyperdatum/core.py:63, 
in VyperCore.log_error(self, msg, exception)                                                         
     61 self.logger.error(msg)
     62 if exception:                                                
---> 63     raise exception(msg)                                                                                                                                                                      

ValueError: Output datum insufficently specified
```

**Comment by FariborzDaneshvar-NOAA** [comment]
I also used the command from the [test function](https://github.com/noaa-ocs-hydrography/vyperdatum/blob/28b63b36195b90b4a32872b0bb5e517d90b70457/tests/test_points.py#L39C5-L39C120) (see below), but still getting `ValueError: Output datun insufficiently specifed` !

`vp.transform_points((6319, 'ellipse'), 'mllw', x, y, z=z, include_vdatum_uncertainty=False, sample_distance=0.0005)`
